import Head from 'next/head'
import Image from 'next/image'
import logo from '../assets/logo.svg';
import Experience from '../components/Experience';
import Header from '../components/Header';
import Hero from '../components/Header/Hero';
import HowItWorks from '../components/HowItWorks';
import Roadmap from '../components/Roadmap';
import Trade from '../components/Trade';
import Token from '../components/Token';
import Faq from '../components/Faq';
import Footer from '../components/Footer';

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Lumina</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
        <Header />
        <Hero />
        <Experience />
        <Trade />
        <HowItWorks />
        <Roadmap />
        <Token />
        <Faq />
        <Footer />
      </div>
        
    </div>
  )
}
